import { Project, User } from "./types";

export const invoice: Project['invoice'][0] = {
  id: 631,
  client_id: 330,
  details: {
    plan_id: 21,
    month: "1",
    tax_percent: 0.09,
    tax: 930000.0599999999,
  },
  from_date: "1402-02-12 11:48:47",
  to_date: "1402-03-12 11:48:47",
  is_paid: false,
  created_at: "1402-02-12 11:48:47",
  updated_at: "1402-02-12 11:48:47",
  cost: "10333334",
  type: "mop",
  invoice_number: null,
  cost_in_string: "10,333,334",
  status: "pending",
  final_price: 11263334.06,
  balance: 4666666,
  plan: {
    id: 21,
    name: "پنج",
    cost_per_month: 15000000,
    request_per_day: 2000000,
    cost_per_year: {
      en: 180000000,
      fa: "۱۸۰۰۰۰۰۰۰",
    },
  },
};

export const user: User = {
  id: "055a411a-cc4b-45f6-95b1-5fc25dc1be17",
  name: "\u062f\u0646\u06cc",
  email: "dansfancymaths@gmail.com",
  address:
    "\u0627\u062f\u0631\u0633 \u062f\u0648\u0628\u0627\u0631\u0647 \u0639\u0648\u0636 \u0634\u062f",
  username: "dansfancymaths@gmail.com",
  client_id: 37,
  scopes: ["basic"],
  created_at: "1402-01-23 14:20:37",
  updated_at: "1402-02-12 11:48:03",
  mobile: "09125244515",
  is_disabled: false,
  image: null,
  national_number: "1231231231",
  company: "\u06cc\u0633\u0628",
  postalcode: "1849419722",
  telephone: "02155313421",
  national_identity: "21312321",
  financial_code: "123123123222",
  account_type: "natural",
  is_hardcoded: false,
  max_projects_count: 2,
  last_login: "1402-02-12 11:48:03",
  expiration_time: null,
  start_time: null,
  is_mobile_verified: true,
  is_email_verified: true,
  alerts: [],
  roles: [
    {
      id: 2,
      name: "basic",
      scope: null,
      title: null,
      user_count: 134,
      pivot: { user_id: "055a411a-cc4b-45f6-95b1-5fc25dc1be17", role_id: 2 },
      permissions: [
        {
          id: 18,
          domain: "users",
          action: "read.one",
          access: "self",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 18 },
        },
        {
          id: 19,
          domain: "users",
          action: "create",
          access: "self",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 19 },
        },
        {
          id: 20,
          domain: "users",
          action: "update",
          access: "self",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 20 },
        },
        {
          id: 21,
          domain: "users",
          action: "delete",
          access: "self",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 21 },
        },
        {
          id: 27,
          domain: "clients",
          action: "read.one",
          access: "self",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 27 },
        },
        {
          id: 28,
          domain: "clients",
          action: "read.all",
          access: "self",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 28 },
        },
        {
          id: 29,
          domain: "clients",
          action: "create",
          access: "self",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 29 },
        },
        {
          id: 30,
          domain: "clients",
          action: "update",
          access: "self",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 30 },
        },
        {
          id: 31,
          domain: "clients",
          action: "delete",
          access: "self",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 31 },
        },
        {
          id: 111,
          domain: "clients",
          action: "read.all",
          access: "subset",
          subdomain: "available-plans",
          description: "",
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 111 },
        },
        {
          id: 184,
          domain: "plans",
          action: "read.all",
          access: "all",
          subdomain: "",
          description: "",
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 2, permission_id: 184 },
        },
      ],
    },
    {
      id: 10,
      name: "creator",
      scope: "my",
      title: "\u0633\u0627\u0632\u0646\u062f\u0647",
      user_count: 125,
      pivot: { user_id: "055a411a-cc4b-45f6-95b1-5fc25dc1be17", role_id: 10 },
      permissions: [
        {
          id: 67,
          domain: "views",
          action: "update",
          access: "all",
          subdomain: "share",
          description: "share by link, password",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 67 },
        },
        {
          id: 68,
          domain: "views",
          action: "create",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 68 },
        },
        {
          id: 69,
          domain: "views",
          action: "read.all",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 69 },
        },
        {
          id: 70,
          domain: "views",
          action: "read.one",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 70 },
        },
        {
          id: 71,
          domain: "views",
          action: "update",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 71 },
        },
        {
          id: 72,
          domain: "views",
          action: "delete",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 72 },
        },
        {
          id: 73,
          domain: "services",
          action: "read.one",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 73 },
        },
        {
          id: 74,
          domain: "services",
          action: "read.all",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 74 },
        },
        {
          id: 75,
          domain: "services",
          action: "update",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 75 },
        },
        {
          id: 76,
          domain: "services",
          action: "delete",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 76 },
        },
        {
          id: 77,
          domain: "services",
          action: "create",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 77 },
        },
        {
          id: 78,
          domain: "services",
          action: "update",
          access: "all",
          subdomain: "share",
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 78 },
        },
        {
          id: 81,
          domain: "datasources",
          action: "update",
          access: "all",
          subdomain: "share",
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 81 },
        },
        {
          id: 82,
          domain: "datasources",
          action: "read.one",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 82 },
        },
        {
          id: 83,
          domain: "datasources",
          action: "read.all",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 83 },
        },
        {
          id: 84,
          domain: "datasources",
          action: "update",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 84 },
        },
        {
          id: 85,
          domain: "datasources",
          action: "delete",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 85 },
        },
        {
          id: 86,
          domain: "datasources",
          action: "create",
          access: "all",
          subdomain: null,
          description: "",
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 86 },
        },
        {
          id: 201,
          domain: "datasources",
          action: "create",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 201 },
        },
        {
          id: 202,
          domain: "datasources",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 202 },
        },
        {
          id: 203,
          domain: "datasources",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 203 },
        },
        {
          id: 204,
          domain: "datasources",
          action: "update",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 204 },
        },
        {
          id: 205,
          domain: "datasources",
          action: "delete",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 205 },
        },
        {
          id: 207,
          domain: "datasources",
          action: "update",
          access: "subset",
          subdomain: "share",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 207 },
        },
        {
          id: 208,
          domain: "tiles",
          action: "create",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 208 },
        },
        {
          id: 209,
          domain: "tiles",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 209 },
        },
        {
          id: 197,
          domain: "tiles",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 197 },
        },
        {
          id: 210,
          domain: "tiles",
          action: "update",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 210 },
        },
        {
          id: 211,
          domain: "tiles",
          action: "delete",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 211 },
        },
        {
          id: 213,
          domain: "tiles",
          action: "update",
          access: "subset",
          subdomain: "share",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 213 },
        },
        {
          id: 214,
          domain: "tiles",
          action: "create",
          access: "subset",
          subdomain: "styles",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 214 },
        },
        {
          id: 196,
          domain: null,
          action: "create",
          access: "subset",
          subdomain: null,
          description: null,
          service: "tile",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 196 },
        },
        {
          id: 215,
          domain: "layers",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "tile",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 215 },
        },
        {
          id: 216,
          domain: "layers",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "tile",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 216 },
        },
        {
          id: 217,
          domain: "search",
          action: "create",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 217 },
        },
        {
          id: 218,
          domain: "search",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 218 },
        },
        {
          id: 199,
          domain: "search",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 199 },
        },
        {
          id: 219,
          domain: "search",
          action: "update",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 219 },
        },
        {
          id: 220,
          domain: "search",
          action: "delete",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 220 },
        },
        {
          id: 222,
          domain: "search",
          action: "update",
          access: "subset",
          subdomain: "share",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 222 },
        },
        {
          id: 223,
          domain: null,
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "search",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 223 },
        },
        {
          id: 224,
          domain: "meta",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "search",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 224 },
        },
        {
          id: 225,
          domain: "identify",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "search",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 225 },
        },
        {
          id: 226,
          domain: "nearest",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "search",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 226 },
        },
        {
          id: 227,
          domain: "views",
          action: "create",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 227 },
        },
        {
          id: 228,
          domain: "views",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 228 },
        },
        {
          id: 229,
          domain: "views",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 229 },
        },
        {
          id: 230,
          domain: "views",
          action: "update",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 230 },
        },
        {
          id: 231,
          domain: "views",
          action: "delete",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 231 },
        },
        {
          id: 233,
          domain: "views",
          action: "update",
          access: "subset",
          subdomain: "share",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 233 },
        },
        {
          id: 234,
          domain: "views",
          action: "read.all",
          access: "subset",
          subdomain: "services",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 234 },
        },
        {
          id: 235,
          domain: "views",
          action: "read.one",
          access: "subset",
          subdomain: "services",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 235 },
        },
        {
          id: 236,
          domain: "views",
          action: "create",
          access: "subset",
          subdomain: "services",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 236 },
        },
        {
          id: 237,
          domain: "views",
          action: "update",
          access: "subset",
          subdomain: "services",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 237 },
        },
        {
          id: 238,
          domain: "views",
          action: "delete",
          access: "subset",
          subdomain: "services",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 238 },
        },
        {
          id: 239,
          domain: "regional_search",
          action: "create",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 239 },
        },
        {
          id: 240,
          domain: "regional_search",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 240 },
        },
        {
          id: 198,
          domain: "regional_search",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 198 },
        },
        {
          id: 241,
          domain: "regional_search",
          action: "update",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 241 },
        },
        {
          id: 242,
          domain: "regional_search",
          action: "delete",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 242 },
        },
        {
          id: 244,
          domain: "regional_search",
          action: "update",
          access: "subset",
          subdomain: "share",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 244 },
        },
        {
          id: 245,
          domain: "styles",
          action: "read.all",
          access: "subset",
          subdomain: "data",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 245 },
        },
        {
          id: 246,
          domain: "styles",
          action: "read.one",
          access: "subset",
          subdomain: "data",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 246 },
        },
        {
          id: 13,
          domain: "users",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 13 },
        },
        {
          id: 16,
          domain: "users",
          action: "update",
          access: "subset",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 16 },
        },
        {
          id: 24,
          domain: "clients",
          action: "create",
          access: "subset",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 24 },
        },
        {
          id: 22,
          domain: "clients",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 22 },
        },
        {
          id: 23,
          domain: "clients",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 23 },
        },
        {
          id: 25,
          domain: "clients",
          action: "update",
          access: "subset",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 25 },
        },
        {
          id: 26,
          domain: "clients",
          action: "delete",
          access: "subset",
          subdomain: null,
          description: null,
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 26 },
        },
        {
          id: 62,
          domain: "clients",
          action: "update",
          access: "subset",
          subdomain: "pause",
          description: "",
          service: "register",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 62 },
        },
        {
          id: 262,
          domain: "tables",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 262 },
        },
        {
          id: 263,
          domain: "tables",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 263 },
        },
        {
          id: 264,
          domain: "tables",
          action: "read.one",
          access: "subset",
          subdomain: "rows",
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 264 },
        },
        {
          id: 265,
          domain: "tables",
          action: "read.all",
          access: "subset",
          subdomain: "rows",
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 265 },
        },
        {
          id: 266,
          domain: "tables",
          action: "create",
          access: "subset",
          subdomain: "rows",
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 266 },
        },
        {
          id: 267,
          domain: "tables",
          action: "update",
          access: "subset",
          subdomain: "rows",
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 267 },
        },
        {
          id: 268,
          domain: "tables",
          action: "delete",
          access: "subset",
          subdomain: "rows",
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 268 },
        },
        {
          id: 269,
          domain: "tables",
          action: "read.all",
          access: "subset",
          subdomain: "columns",
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 269 },
        },
        {
          id: 270,
          domain: "tables",
          action: "read.one",
          access: "subset",
          subdomain: "columns",
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 270 },
        },
        {
          id: 271,
          domain: "tables",
          action: "create",
          access: "subset",
          subdomain: "columns",
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 271 },
        },
        {
          id: 272,
          domain: "tables",
          action: "update",
          access: "subset",
          subdomain: "columns",
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 272 },
        },
        {
          id: 273,
          domain: "tables",
          action: "delete",
          access: "subset",
          subdomain: "columns",
          description: null,
          service: "editor",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 273 },
        },
        {
          id: 274,
          domain: "enrichments",
          action: "read.all",
          access: "subset",
          subdomain: "tasks",
          description: null,
          service: "dataflow",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 274 },
        },
        {
          id: 275,
          domain: "enrichments",
          action: "read.one",
          access: "subset",
          subdomain: "tasks",
          description: null,
          service: "dataflow",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 275 },
        },
        {
          id: 276,
          domain: "enrichments",
          action: "create",
          access: "subset",
          subdomain: "tasks",
          description: null,
          service: "dataflow",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 276 },
        },
        {
          id: 277,
          domain: "enrichments",
          action: "delete",
          access: "subset",
          subdomain: "tasks",
          description: null,
          service: "dataflow",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 277 },
        },
        {
          id: 278,
          domain: "enrichments",
          action: "read.all",
          access: "subset",
          subdomain: "types",
          description: null,
          service: "dataflow",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 278 },
        },
        {
          id: 279,
          domain: "enrichments",
          action: "read.one",
          access: "subset",
          subdomain: "types",
          description: null,
          service: "dataflow",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 279 },
        },
        {
          id: 280,
          domain: "import",
          action: "create",
          access: "subset",
          subdomain: null,
          description: null,
          service: "transfer",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 280 },
        },
        {
          id: 281,
          domain: "imports",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "transfer",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 281 },
        },
        {
          id: 282,
          domain: "imports",
          action: "create",
          access: "subset",
          subdomain: "external_database_test",
          description: null,
          service: "transfer",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 282 },
        },
        {
          id: 283,
          domain: "imports",
          action: "create",
          access: "subset",
          subdomain: "external_database",
          description: null,
          service: "transfer",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 283 },
        },
        {
          id: 284,
          domain: "export",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "transfer",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 284 },
        },
        {
          id: 285,
          domain: null,
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "log",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 285 },
        },
        {
          id: 288,
          domain: "tiles",
          action: "update",
          access: "subset",
          subdomain: "styles",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 288 },
        },
        {
          id: 289,
          domain: "mapping",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "log",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 289 },
        },
        {
          id: 290,
          domain: "mapping",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "log",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 290 },
        },
        {
          id: 304,
          domain: "share",
          action: "create",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 304 },
        },
        {
          id: 306,
          domain: "enrichments",
          action: "update",
          access: "subset",
          subdomain: "tasks",
          description: null,
          service: "dataflow",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 306 },
        },
        {
          id: 307,
          domain: "services",
          action: "create",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 307 },
        },
        {
          id: 308,
          domain: "services",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 308 },
        },
        {
          id: 309,
          domain: "services",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 309 },
        },
        {
          id: 310,
          domain: "services",
          action: "update",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 310 },
        },
        {
          id: 311,
          domain: "services",
          action: "delete",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 311 },
        },
        {
          id: 315,
          domain: "services",
          action: "update",
          access: "subset",
          subdomain: "share",
          description: null,
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 315 },
        },
        {
          id: 324,
          domain: null,
          action: "read.all",
          access: "subset",
          subdomain: "export",
          description: null,
          service: "search",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 324 },
        },
        {
          id: 331,
          domain: "mappings",
          action: "read.all",
          access: "subset",
          subdomain: null,
          description: null,
          service: "log",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 331 },
        },
        {
          id: 332,
          domain: "mappings",
          action: "read.one",
          access: "subset",
          subdomain: null,
          description: null,
          service: "log",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 332 },
        },
        {
          id: 330,
          domain: "services",
          action: "delete",
          access: "subset",
          subdomain: "share",
          description: null,
          service: "mym",
          identifier: null,
          title: "\r",
          pivot: { role_id: 10, permission_id: 330 },
        },
        {
          id: 317,
          domain: "share",
          action: "delete",
          access: "subset",
          subdomain: null,
          description: null,
          service: "mym",
          identifier: null,
          title: null,
          pivot: { role_id: 10, permission_id: 317 },
        },
      ],
    },
  ],
  my_app: null,
  action_areas: [],
  action_time: [],
};